---
title: "Statistics III: Generalized Linear Models"
subtitle: "CdL SSE"
author: "[Tommaso Rigon]{.orange}"
institute: "_Università degli Studi di Milano-Bicocca_"
lang: en
page-layout: full
execute:
  cache: false
format:
  html:
    html-math-method: katex
    echo: true
    callout-appearance: minimal
    theme: [simplex, template.css]
    toc: true
    toc-title: Table of contents
    embed-resources: false
    code-line-numbers: true
    smooth-scroll: true
    fig-dpi: 250
editor: 
  markdown: 
    wrap: 72
editor_options: 
  chunk_output_type: console
---

This is the website of the **Statistica III** course (6 CFU) of the "*Corso di Laurea Triennale in Scienze Statistiche ed Economiche* (SSE)", Università degli Studi di Milano-Bicocca. **Statistica III** is a monographic course on [Generalized Linear Models]{.blue} (GLMs).

This is a [B.Sc.-level]{.orange} course, but there are some prerequisites: it is assumed that you have already been exposed to:

  - [Simple linear regression and descriptive statistics]{.blue}, e.g. from [_Statistica I_](https://tommasorigon.github.io/StatI/);
  - [Inferential statistics]{.orange}, e.g. from _Statistica II_;
  - [Linear models]{.grey}, e.g. from _Analisi Statistica Multivariata_ and _Econometria_;
  - [R software]{.grey}, e.g. from [_Analisi Statistica Multivariata_](https://tommasorigon.github.io/introR/).

Regression is such an important topic that the [tour]{.orange} will [continue]{.orange} at  [Data Mining](https://tommasorigon.github.io/datamining/).


## Teaching material

#### Recommended textbooks (ITA)

- Salvan, A., Sartori, N. and L. Pace. 2020. [*Modelli Lineari Generalizzati*](https://link.springer.com/chapter/10.1007/978-88-470-4002-1_2). Springer.
- Azzalini, A. 2008. [*Inferenza Statistica: Una Presentazione Basata sul Concetto di Verosimiglianza*](https://link.springer.com/book/9788847001305). Springer

    
#### Recommended textbooks (ENG)

- Agresti, A. 2015. [*Foundations of Linear and Generalized Linear Models*](https://www.wiley.com/en-us/Foundations+of+Linear+and+Generalized+Linear+Models-p-9781118730034). Wiley.
- McCullagh, P., and J. A. Nelder. 1989. [*Generalized Linear Models*](https://www.taylorfrancis.com/books/mono/10.1201/9780203753736/generalized-linear-models-mccullagh). Second Edition. Springer.

#### Slides and lecture notes

The slides are meant to be used in HTML. However, if you *really* want
to convert the HTML slides into pdf files, you can [follow the
instruction of the quarto
documentation](https://quarto.org/docs/presentations/revealjs/presenting.html#print-to-pdf).

| Topic | Notes | Slides | Further material |
|-------------------|------------------|------------------|------------------|
| **Introduction** | [Introduction](slides/un_intro.html) | [Slides Introduction](slides/un_intro_slides.html) |  |
| | **GENERAL THEORY** | | |
| **Linear models and misspecification** | [Unit A](slides/un_A.html) | [Slides Unit A](slides/un_A_slides.html) |  |
| *Exercises* | [Exercises A](exe/exe_A.html) |  |  |
| Lab 1 |  [`lab1.R`](code/lab1.R) | | |
| **Generalized Linear Models** | [Unit B](slides/un_B.html) | [Slides Unit B](slides/un_B_slides.html)|  |
| *Exercises* | [Exercises B](exe/exe_B.html) |  |  |
| Lab 2 | [`lab2.R`](code/lab2.R) | | |
| Lab 3 | [`lab3.R`](code/lab3.R)| | |
| | **NOTABLE MODELS** | | |
| **Binary and binomial regression** | [Unit C] | [Slides Unit C] |  |
| Lab 4 | [`lab4.R`] | | |
| *Exercises* | [Exercises C](exe/exe_C.html) |  |  |
| **Poisson regression** | [Unit D] | [Slides Unit D] |  |
| Lab 5 | [`lab5.R`] | | |
| *Exercises* | [Exercises D] |  |  |
| Lab 6 | [`lab6.R`] | | |
| | **ADVANCED TOPICS** | | |
| **Quasi-likelihoods** | [Unit E] | [Slides Unit E] |  |
| Lab 7 | [`lab7.R`] | | |
| *Exercises* | [Exercises F] |  |  |

## Previous exams (ITA)

Example of previous exams are provided below.

| Date | Dataset | Questions (ITA) | Solution (ITA) |
|------|---------|-----------|----------|
| 9 July 2014 | [`orings`](https://search.r-project.org/CRAN/refmans/faraway/html/orings.html) | [Exam](exams/2014_07_09.html) |  |
| 29 April 2015 | [`ships`](https://search.r-project.org/CRAN/refmans/MASS/html/ships.html) | [Exam](exams/2015_04_29.html) | |


<!-- ## Prerequisites -->

<!-- Knowledge of the topics (i) linear algebra, (ii) linear models is highly recommended. -->

<!-- Knowledge of topics covered in the courses Probability and Statistics M -->

<!-- and Advanced Statistics M is also highly recommended. -->

## Acknowledgments

I would like to kindly acknowledge Sonia Migliorati for sharing her material of a previous edition of this course. 

<!-- I have made use of several other books, scientific articles, and datasets to complement the main textbooks. They are all cited at the end of each unit.  -->

Students are encouraged to consult the books: these slides are just a concise summary.

All the mistakes still present are mine.

------------------------------------------------------------------------
